### ISSUE TITLE
Will the paper be available on this github?

### ISSUE THREAD

**Issue by layssi** [nkuhzx/ssDRL#1]

**Comment by nkuhzx** [comment]
our paper is available in: [Springer IJSR](https://link.springer.com/content/pdf/10.1007/s12369-021-00838-x.pdf)

**Comment by nkuhzx** [comment]
Dear layssi:
Our paper is available in: [Springer IJSR](https://link.springer.com/content/pdf/10.1007/s12369-021-00838-x.pdf)
